services:
  postgres:
    image: postgres:16
    container_name: estoque-db
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: estoque
      POSTGRES_PASSWORD: estoque
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - estoque-data:/var/lib/postgresql/data

volumes:
  estoque-data:
